version: '3.9'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - db_data:/data/storage.db
    environment:
      - UVICORN_RELOAD=True

volumes:
  db_data:
